import React from 'react';
import Header from '../components/Header';
import PromptForm from '../components/PromptForm';
import CodeEditor from '../components/CodeEditor';
import LivePreview from '../components/LivePreview';
import VersionHistory from '../components/VersionHistory';

export default function HomePage() {
  const [code, setCode] = React.useState(`export default function App() {
  return (
    <div style={{ padding: '20px', textAlign: 'center', fontFamily: 'Arial, sans-serif' }}>
      <h2>Welcome to Ryze AI</h2>
      <p>Describe your UI above to get started!</p>
    </div>
  );
}`);
  const [versions, setVersions] = React.useState([]);
  const [loading, setLoading] = React.useState(false);

  const handlePrompt = async (prompt) => {
    setLoading(true);
    try {
      const response = await fetch(`${process.env.REACT_APP_API_URL || 'http://localhost:5000'}/api/ui/generate`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ prompt }),
      });

      if (!response.ok) {
        throw new Error(`API Error: ${response.statusText}`);
      }

      const data = await response.json();
      const generated = data.code || `export default function App() {
  return (
    <div style={{ padding: '40px', fontFamily: 'Arial, sans-serif', maxWidth: '1200px', margin: '0 auto' }}>
      <h1>✨ ${prompt}</h1>
      <p>Generated by AI</p>
    </div>
  );
}`;
      setCode(generated);
      setVersions([{ code: generated, createdAt: new Date() }, ...versions]);
    } catch (error) {
      console.error('Error generating UI:', error);
      alert('Failed to generate UI. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const handleSelectVersion = (v) => {
    setCode(v.code);
  };

  return (
    <div style={{ backgroundColor: '#f9fafb', minHeight: '100vh' }}>
      <Header />
      
      {/* Hero Section */}
      <div style={{ background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)', color: 'white', padding: '60px 20px', textAlign: 'center' }}>
        <h1 style={{ fontSize: '2.5rem', marginBottom: '1rem', fontWeight: 'bold' }}>Ryze AI</h1>
        <p style={{ fontSize: '1.2rem', maxWidth: '600px', margin: '0 auto 30px' }}>Generate modern, beautiful React UI components from natural language descriptions powered by AI</p>
      </div>

      {/* Main Container */}
      <div style={{ maxWidth: '1400px', margin: '0 auto', padding: '2rem 1rem' }}>
        <div style={{ display: 'flex', gap: '2rem', flexWrap: 'wrap' }}>
          {/* Left Column - Input & Editor */}
          <div style={{ flex: '2 1 600px' }}>
            <div style={{ backgroundColor: 'white', borderRadius: '12px', padding: '1.5rem', boxShadow: '0 4px 6px rgba(0,0,0,0.1)' }}>
              <h2 style={{ marginTop: 0, color: '#1f2937' }}>Create Your UI</h2>
              <PromptForm onSubmit={handlePrompt} />
              <CodeEditor code={code} onChange={setCode} />
              <LivePreview code={code} />
            </div>
          </div>

          {/* Right Column - Version History */}
          <div style={{ flex: '1 1 300px' }}>
            <div style={{ backgroundColor: 'white', borderRadius: '12px', padding: '1.5rem', boxShadow: '0 4px 6px rgba(0,0,0,0.1)' }}>
              <h2 style={{ marginTop: 0, color: '#1f2937' }}>Version History</h2>
              <VersionHistory versions={versions} onSelect={handleSelectVersion} />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}